import { describe, it } from 'vitest';
import {
	expectResolvableVersion,
	GENERATED_LOCKFILE_TEST_ENABLED,
	runCommand,
	withTempProject,
} from './generated-test-helpers';

const describeGenerated = GENERATED_LOCKFILE_TEST_ENABLED
	? describe
	: describe.skip;

describeGenerated('generated bun.lock', () => {
	it('parses bun.lock generated by bun add --dev @tombi-toml/tombi', async () => {
		await withTempProject('setup-tombi-bun-', async (projectDir) => {
			runCommand('bun init -y', projectDir);
			runCommand(
				'bun add --dev --save-text-lockfile @tombi-toml/tombi',
				projectDir,
			);
			await expectResolvableVersion(projectDir, 'bun.lock');
		});
	}, 180_000);
});
