import { describe, it } from 'vitest';
import {
	expectResolvableVersion,
	GENERATED_LOCKFILE_TEST_ENABLED,
	runCommand,
	withTempProject,
} from './generated-test-helpers';

const describeGenerated = GENERATED_LOCKFILE_TEST_ENABLED
	? describe
	: describe.skip;

describeGenerated('generated pnpm-lock.yaml', () => {
	it('parses pnpm-lock.yaml generated by pnpm add -D @tombi-toml/tombi', async () => {
		await withTempProject('setup-tombi-pnpm-', async (projectDir) => {
			runCommand('npm init -y', projectDir);
			runCommand('pnpm add -D @tombi-toml/tombi', projectDir);
			await expectResolvableVersion(projectDir, 'pnpm-lock.yaml');
		});
	}, 180_000);
});
