import { describe, it } from 'vitest';
import {
	expectResolvableVersion,
	GENERATED_LOCKFILE_TEST_ENABLED,
	runCommand,
	withTempProject,
} from './generated-test-helpers';

const describeGenerated = GENERATED_LOCKFILE_TEST_ENABLED
	? describe
	: describe.skip;

describeGenerated('generated poetry.lock', () => {
	it('parses poetry.lock generated by poetry add --group dev tombi', async () => {
		await withTempProject('setup-tombi-poetry-', async (projectDir) => {
			runCommand(
				'poetry init --name setup-tombi-lockfile --python ^3.11 --no-interaction',
				projectDir,
			);
			runCommand('poetry add --group dev tombi', projectDir);
			await expectResolvableVersion(projectDir, 'poetry.lock');
		});
	}, 180_000);
});
