import { describe, it } from 'vitest';
import {
	expectResolvableVersion,
	GENERATED_LOCKFILE_TEST_ENABLED,
	runCommand,
	withTempProject,
} from './generated-test-helpers';

const describeGenerated = GENERATED_LOCKFILE_TEST_ENABLED
	? describe
	: describe.skip;

describeGenerated('generated yarn.lock', () => {
	it('parses yarn.lock generated by yarn add --dev @tombi-toml/tombi', async () => {
		await withTempProject('setup-tombi-yarn-', async (projectDir) => {
			runCommand('yarn init -y', projectDir);
			runCommand('yarn add --dev @tombi-toml/tombi', projectDir);
			await expectResolvableVersion(projectDir, 'yarn.lock');
		});
	}, 180_000);
});
